# Generated by Django 3.0.4 on 2020-03-13 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleauthuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
